-- Add members column to trips table
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS members jsonb DEFAULT '["Me"]'::jsonb;

-- Create Expenses Table
CREATE TABLE IF NOT EXISTS public.expenses (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips on delete cascade not null,
  payer text not null,
  amount numeric not null,
  description text not null,
  date date default CURRENT_DATE,
  category text default 'Misc',
  split_with jsonb default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for expenses
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;

-- Policies for expenses
CREATE POLICY "Users can view expenses of their trips" ON public.expenses FOR SELECT USING (EXISTS (SELECT 1 FROM public.trips WHERE trips.id = expenses.trip_id AND trips.user_id = auth.uid()));
CREATE POLICY "Users can insert expenses to their trips" ON public.expenses FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM public.trips WHERE trips.id = expenses.trip_id AND trips.user_id = auth.uid()));
CREATE POLICY "Users can update expenses of their trips" ON public.expenses FOR UPDATE USING (EXISTS (SELECT 1 FROM public.trips WHERE trips.id = expenses.trip_id AND trips.user_id = auth.uid()));
CREATE POLICY "Users can delete expenses of their trips" ON public.expenses FOR DELETE USING (EXISTS (SELECT 1 FROM public.trips WHERE trips.id = expenses.trip_id AND trips.user_id = auth.uid()));
