-- Enable Row Level Security
alter default privileges in schema public grant all on tables to postgres, anon, authenticated, service_role;

-- Trips Table
create table public.trips (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  start_date date,
  end_date date,
  city text,
  hero_image text,
  visa_status text,
  visa_info text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.trips enable row level security;
create policy "Users can view their own trips" on public.trips for select using (auth.uid() = user_id);
create policy "Users can insert their own trips" on public.trips for insert with check (auth.uid() = user_id);
create policy "Users can update their own trips" on public.trips for update using (auth.uid() = user_id);
create policy "Users can delete their own trips" on public.trips for delete using (auth.uid() = user_id);

-- Itinerary Items Table
create table public.itinerary_items (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips on delete cascade not null,
  day date,
  time time,
  activity text not null,
  location text,
  notes text,
  cost numeric,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.itinerary_items enable row level security;
create policy "Users can view itinerary items of their trips" on public.itinerary_items for select using (exists (select 1 from public.trips where trips.id = itinerary_items.trip_id and trips.user_id = auth.uid()));
create policy "Users can insert itinerary items to their trips" on public.itinerary_items for insert with check (exists (select 1 from public.trips where trips.id = itinerary_items.trip_id and trips.user_id = auth.uid()));
create policy "Users can update itinerary items of their trips" on public.itinerary_items for update using (exists (select 1 from public.trips where trips.id = itinerary_items.trip_id and trips.user_id = auth.uid()));
create policy "Users can delete itinerary items of their trips" on public.itinerary_items for delete using (exists (select 1 from public.trips where trips.id = itinerary_items.trip_id and trips.user_id = auth.uid()));

-- Packing Items Table
create table public.packing_items (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips on delete cascade not null,
  item text not null,
  category text default 'Misc',
  is_packed boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.packing_items enable row level security;
create policy "Users can view packing items of their trips" on public.packing_items for select using (exists (select 1 from public.trips where trips.id = packing_items.trip_id and trips.user_id = auth.uid()));
create policy "Users can insert packing items to their trips" on public.packing_items for insert with check (exists (select 1 from public.trips where trips.id = packing_items.trip_id and trips.user_id = auth.uid()));
create policy "Users can update packing items of their trips" on public.packing_items for update using (exists (select 1 from public.trips where trips.id = packing_items.trip_id and trips.user_id = auth.uid()));
create policy "Users can delete packing items of their trips" on public.packing_items for delete using (exists (select 1 from public.trips where trips.id = packing_items.trip_id and trips.user_id = auth.uid()));

-- Documents Table
create table public.documents (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips on delete cascade not null,
  title text not null,
  content text,
  file_url text,
  type text default 'note', -- 'note', 'visa', 'passport'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.documents enable row level security;
create policy "Users can view documents of their trips" on public.documents for select using (exists (select 1 from public.trips where trips.id = documents.trip_id and trips.user_id = auth.uid()));
create policy "Users can insert documents to their trips" on public.documents for insert with check (exists (select 1 from public.trips where trips.id = documents.trip_id and trips.user_id = auth.uid()));
create policy "Users can update documents of their trips" on public.documents for update using (exists (select 1 from public.trips where trips.id = documents.trip_id and trips.user_id = auth.uid()));
create policy "Users can delete documents of their trips" on public.documents for delete using (exists (select 1 from public.trips where trips.id = documents.trip_id and trips.user_id = auth.uid()));

-- Tickets (Wallet) Table
create table public.tickets (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips on delete cascade not null,
  type text not null, -- 'Flight', 'Train', 'Bus', 'Attraction'
  provider text,
  reference_number text,
  departure_time timestamp with time zone,
  arrival_time timestamp with time zone,
  file_url text,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.tickets enable row level security;
create policy "Users can view tickets of their trips" on public.tickets for select using (exists (select 1 from public.trips where trips.id = tickets.trip_id and trips.user_id = auth.uid()));
create policy "Users can insert tickets to their trips" on public.tickets for insert with check (exists (select 1 from public.trips where trips.id = tickets.trip_id and trips.user_id = auth.uid()));
create policy "Users can update tickets of their trips" on public.tickets for update using (exists (select 1 from public.trips where trips.id = tickets.trip_id and trips.user_id = auth.uid()));
create policy "Users can delete tickets of their trips" on public.tickets for delete using (exists (select 1 from public.trips where trips.id = tickets.trip_id and trips.user_id = auth.uid()));

-- Accommodation Table
create table public.accommodation (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips on delete cascade not null,
  name text not null,
  address text,
  check_in date,
  check_out date,
  booking_reference text,
  notes text,
  cost numeric,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.accommodation enable row level security;
create policy "Users can view accommodation of their trips" on public.accommodation for select using (exists (select 1 from public.trips where trips.id = accommodation.trip_id and trips.user_id = auth.uid()));
create policy "Users can insert accommodation to their trips" on public.accommodation for insert with check (exists (select 1 from public.trips where trips.id = accommodation.trip_id and trips.user_id = auth.uid()));
create policy "Users can update accommodation of their trips" on public.accommodation for update using (exists (select 1 from public.trips where trips.id = accommodation.trip_id and trips.user_id = auth.uid()));
create policy "Users can delete accommodation of their trips" on public.accommodation for delete using (exists (select 1 from public.trips where trips.id = accommodation.trip_id and trips.user_id = auth.uid()));

-- Transport Table
create table public.transport (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips on delete cascade not null,
  type text not null,
  provider text,
  departure_location text,
  arrival_location text,
  departure_time timestamp with time zone,
  arrival_time timestamp with time zone,
  booking_reference text,
  notes text,
  cost numeric,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.transport enable row level security;
create policy "Users can view transport of their trips" on public.transport for select using (exists (select 1 from public.trips where trips.id = transport.trip_id and trips.user_id = auth.uid()));
create policy "Users can insert transport to their trips" on public.transport for insert with check (exists (select 1 from public.trips where trips.id = transport.trip_id and trips.user_id = auth.uid()));
create policy "Users can update transport of their trips" on public.transport for update using (exists (select 1 from public.trips where trips.id = transport.trip_id and trips.user_id = auth.uid()));
create policy "Users can delete transport of their trips" on public.transport for delete using (exists (select 1 from public.trips where trips.id = transport.trip_id and trips.user_id = auth.uid()));
